version: '3.8'
services:
  db:
    container_name: db
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    container_name: frontend
    image: anton60874022/foodgram_frontend:v1
    volumes:
          - ../frontend/:/app/result_build/
    depends_on:
      - backend
      
  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/ะดั -
    restart: always
    depends_on:
      - backend

  backend:
    container_name: backend
    image: anton60874022/foodgram_backend:v1
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    env_file:
    - ./.env

volumes:
  postgres_data:
  static_value:
  media_value: