version: '2.2'
services:
  db:
    container_name: db
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  frontend:
    container_name: frontend
    image: anton60874022/foodgram_frontend:v1
    volumes:
      - result_build:/app/result_build/build/
    depends_on:
      - backend

  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - '80:80'
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - backend

  backend:
    container_name: backend
    image: anton60874022/foodgram_backend:v1
    restart: always
    depends_on:
      - db
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    env_file:
    - ./.env

volumes:
  result_build:
  postgres_data:
  static_value:
  media_value: